//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackYourTrip.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TrackYourTrip.Core.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Close and new trip ähnelt.
        /// </summary>
        internal static string ActiveTripClose {
            get {
                return ResourceManager.GetString("ActiveTripClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Continue trip ähnelt.
        /// </summary>
        internal static string ActiveTripContinue {
            get {
                return ResourceManager.GetString("ActiveTripContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There is an active Trip stored in background. Would you like to continue this trip? Otherwise it will be closed and deleted. ähnelt.
        /// </summary>
        internal static string ActiveTripPromptText {
            get {
                return ResourceManager.GetString("ActiveTripPromptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Active trip ähnelt.
        /// </summary>
        internal static string ActiveTripTitle {
            get {
                return ResourceManager.GetString("ActiveTripTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add ähnelt.
        /// </summary>
        internal static string AddCommandTitle {
            get {
                return ResourceManager.GetString("AddCommandTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die TrackYourTrip ähnelt.
        /// </summary>
        internal static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete ähnelt.
        /// </summary>
        internal static string DeleteCommandTitle {
            get {
                return ResourceManager.GetString("DeleteCommandTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Are you sure? ähnelt.
        /// </summary>
        internal static string DeleteItemText {
            get {
                return ResourceManager.GetString("DeleteItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fishing area ähnelt.
        /// </summary>
        internal static string FishingAreaPageTitle {
            get {
                return ResourceManager.GetString("FishingAreaPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please mark your fishing area by clicking on the map. ähnelt.
        /// </summary>
        internal static string FishingAreaSetText {
            get {
                return ResourceManager.GetString("FishingAreaSetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fishing areas ähnelt.
        /// </summary>
        internal static string FishingAreasPageTitle {
            get {
                return ResourceManager.GetString("FishingAreasPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die To Second Page ähnelt.
        /// </summary>
        internal static string GoToSecondPageText {
            get {
                return ResourceManager.GetString("GoToSecondPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mainmenu ähnelt.
        /// </summary>
        internal static string MainMenuPageTitle {
            get {
                return ResourceManager.GetString("MainMenuPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Press me ähnelt.
        /// </summary>
        internal static string MainPageButton {
            get {
                return ResourceManager.GetString("MainPageButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Thank you! ähnelt.
        /// </summary>
        internal static string MainPageButtonPressed {
            get {
                return ResourceManager.GetString("MainPageButtonPressed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hello Xamarin! ähnelt.
        /// </summary>
        internal static string MainPageTitle {
            get {
                return ResourceManager.GetString("MainPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Trip overview ähnelt.
        /// </summary>
        internal static string NewTripOverviewPageTitle {
            get {
                return ResourceManager.GetString("NewTripOverviewPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Presettings ähnelt.
        /// </summary>
        internal static string NewTripOverviewPreSettingsPageTitle {
            get {
                return ResourceManager.GetString("NewTripOverviewPreSettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New Trip ähnelt.
        /// </summary>
        internal static string NewTripPageTitle {
            get {
                return ResourceManager.GetString("NewTripPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start! ähnelt.
        /// </summary>
        internal static string NewTripStart {
            get {
                return ResourceManager.GetString("NewTripStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Finish ähnelt.
        /// </summary>
        internal static string SaveCommandTitle {
            get {
                return ResourceManager.GetString("SaveCommandTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Search ähnelt.
        /// </summary>
        internal static string SearchText {
            get {
                return ResourceManager.GetString("SearchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        internal static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Checkin to spot ähnelt.
        /// </summary>
        internal static string SpotCheckinButtonText {
            get {
                return ResourceManager.GetString("SpotCheckinButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Spot ähnelt.
        /// </summary>
        internal static string SpotPageTitle {
            get {
                return ResourceManager.GetString("SpotPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Spots ähnelt.
        /// </summary>
        internal static string SpotsPageTitle {
            get {
                return ResourceManager.GetString("SpotsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please choose a spot type first! ähnelt.
        /// </summary>
        internal static string SpotTypeEmptyText {
            get {
                return ResourceManager.GetString("SpotTypeEmptyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please mark your spot by clicking on to the map. ähnelt.
        /// </summary>
        internal static string SpotTypeSetText {
            get {
                return ResourceManager.GetString("SpotTypeSetText", resourceCulture);
            }
        }
    }
}
